services:
  osticket:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./confs/ost-config.php:/var/www/html/include/ost-config.php
    links:
      - mysql:mysql

  mysql:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    tmpfs:
      - /tmp
      - /var/lock
    environment:
      - MYSQL_USER=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=changeme
      - MYSQL_ROOT_PASSWORD=changeme
